name: Aerokube download test!

on:
  workflow_dispatch

jobs:
  test-aerokube:
    runs-on: ubuntu-latest
    steps:
    - name: install docker dependencies
      run: | 
        sudo apt-get install apt-transport-https ca-certificates curl gnupg
        
    - name: add docker gpg key
      run:  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: install docker
      run:  sudo apt-get install moby-engine moby-cli containerd.io
      
    - name: test aerokube script download time
      run: time curl -Is https://aerokube.com/cm/bash | bash && ./cm selenoid start

